basePath: /
definitions:
  commands.CreateCategoryCommand:
    properties:
      description:
        type: string
      name:
        type: string
    type: object
  dtos.CategoryDto:
    properties:
      createdAt:
        type: string
      description:
        type: string
      id:
        type: integer
      name:
        type: string
    type: object
host: localhost:3000
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Gin Swagger Example API
  version: "1.0"
paths:
  /categories:
    post:
      consumes:
      - application/json
      description: Create new category item
      parameters:
      - description: Category data
        in: body
        name: CreateCategoryRequestDto
        required: true
        schema:
          $ref: '#/definitions/commands.CreateCategoryCommand'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dtos.CategoryDto'
      summary: Create category
      tags:
      - Category
  /categories/{id}:
    get:
      consumes:
      - application/json
      description: Get category by id
      parameters:
      - description: Category ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dtos.CategoryDto'
      summary: Get category
      tags:
      - Category
schemes:
- http
swagger: "2.0"
